### AVAILABLE WALLPAPER THEMES ###
########### la rotonde ###########
#~/Pictures/wallpaper/rotonde/la_rotonde_1920x1080.png
#~/Pictures/wallpaper/rotonde/inside2_not_rotonde_1920x1080.png
#~/Pictures/wallpaper/rotonde/bar_not_rotonde_1920x1080.png
#~/Pictures/wallpaper/rotonde/kitchen2_not_rotonde_1920x1080.png
#~/Pictures/wallpaper/rotonde/back-alley2_not_rotonde_1920x1080.png

########### fantasy ###########
#~/Pictures/wallpaper/fantasy/system02_1920x1080.png
#~/Pictures/wallpaper/fantasy/village_1920x1080.png
#~/Pictures/wallpaper/fantasy/night_talk_1920x1080.png
#~/Pictures/wallpaper/fantasy/drowfight_1920x1080.png
#~/Pictures/wallpaper/fantasy/hordes_1920x1080.png
#~/Pictures/wallpaper/fantasy/epic_battle_with_five_heros_1920x1080.png
#~/Pictures/wallpaper/fantasy/dragons_1920x1080.png

splash = false

wallpaper {
    monitor =
    path = ~/Pictures/wallpaper/fantasy/system01_1920x1080.png
    fit_mode = fill
}
